### ISSUE TITLE
Faces with number of vertices greater or equal than 5 don't display properly

### ISSUE THREAD

**Issue by Blackiris** [jcmellado/hangar#6]
Hi,

The AC3D parser has some difficulties reading faces with at least 5 vertices.
It is fixed in the following commit:

https://sourceforge.net/p/flightgear/sceneryweb/ci/455cb19e0290fef1c238c5641520d40a3b17e00e/

To sum up:
- First issue was normal computation which use only 3 vertices instead of all of them. The fix was to add all of them (like OSG AC3D reader do).
- Then there is a small mistake in the convexe hull extracting (see triangulator.js).

Can you add these fixes?
Thank you for your work!

Regards,
Julien

**Comment by jcmellado** [comment]
Could you provided the file that you are using for testing?

From the library documentation: "Degenerated polygons are discarded. That is, polygons with less than three vertices, polygons with collinear coordinates, polygons with vertices not contained in an only one plane, polygons crossing edges, and so on."

Only the first three vertices are taken for normal computation. That's the expected behaviour.

And about the triangulator.js fix. I don't see it really necessary, because "u" takes the previous value of "v" on each iteration, and that value seems to be always fine.

**Comment by Blackiris** [comment]
Hi Juan,

Thank you for your response,
We had an issue with this model : 
http://scenemodels.flightgear.org/app.php?c=Models&a=view&id=5186 whose 
a great number of faces were invisible using Hangar, but visible in 
FlightGear itself. Some other models also had this issue but not as much 
as this one.
You can download it from "Download model" link.

About triangulator.js, it is possible to have "v = len -1", but in the 
next loop, given that "u= v" and that "len" is drecreased by 1, "u" can 
equal "len". At least, making sure that "u < len" fix the bug.

Of course, feel free to accept this bug fix or not.

Best regards,
Julien Nguyen

**Comment by jcmellado** [comment]
Ok, I'll try to fix the code along this week.

Thanks
